import os
class echo1:
    def fill():
        print("=====================echo-neme-fill======================")
        print("sinon.chr","meebl.chr",sep='    ')
        print("=========================================================")
        input2 = input("name -fill:")
        if input2 == 'sinon.chr':
            print("=========================================================")
            print("   delet-fill[1] exit-no-the-game[2]              info[3]")
            print("                                                         ")
            print("             [4]                 [5]                  [6]")
            print("=========================================================")
            input3 = input("")
            if input3 == '1':
                os.remove("Dignitaries/sinon.chr")
            if input3 == '2':
                print("exit-[sinon]")
            if input3 == '3':
                print("\033[31m┌───────────────┬───────────────────┬─────────┬────────┬─────────────────────────────┬──────┬────────┬──────────┐\033[0m")
                print("\033[31m│      iP▴      │    domain-name    │  Name:  │  game: │         Vendor              │ Sent │ Recvd  │   Seen   │\033[0m")
                print("\033[31m├───────────────┼───────────────────┼─────────┼────────┼─────────────────────────────┼──────┼────────┼──────────┤\033[0m")
                print("\033[31m│ 41.249.167.79 │ ╳╳:╳╳:╳╳:╳╳:╳╳:╳╳ │  sinon  │  ╳╳╳╳  │  PCS Computer Systems GmbH  │ ╳ B  │ ╳ B    │ ╳╳:╳╳:╳╳ │\033[0m")
                print("\033[31m└───────────────┴───────────────────┴─────────┴────────┴─────────────────────────────┴──────┴────────┴──────────┘\033[0m")
                input()
        if input2 == 'meebl.chr':
            print("=========================================================")
            print("   delet-fill[1] exit-no-the-game[2]              info[3]")
            print("                                                         ")
            print("             [4]                 [5]                  [6]")
            print("=========================================================")
            input3 = input("")
            if input3 == '1':
                os.remove("Dignitaries/meebl.chr")
            if input3 == '2':
                print("exit-[meebl]")
            if input3 == '3':
                print("\033[31m┌───────────────┬───────────────────┬─────────┬────────┬─────────────────────────────┬──────┬────────┬──────────┐\033[0m")
                print("\033[31m│      iP▴      │    domain-name    │  Name:  │  game: │         Vendor              │ Sent │ Recvd  │   Seen   │\033[0m")
                print("\033[31m├───────────────┼───────────────────┼─────────┼────────┼─────────────────────────────┼──────┼────────┼──────────┤\033[0m")
                print("\033[31m│   ╳╳.╳.╳.╳╳   │ ╳╳:╳╳:╳╳:╳╳:╳╳:╳╳ │  meebl  │  ╳╳╳╳  │  PCS Computer Systems GmbH  │ ╳ B  │ ╳ B    │ ╳╳:╳╳:╳╳ │\033[0m")
                print("\033[31m└───────────────┴───────────────────┴─────────┴────────┴─────────────────────────────┴──────┴────────┴──────────┘\033[0m")

class echo2:
    def Ai():
        print("=========================================================")
        print("        fills[1]             text[2]        the-places[3]")
        print("                                                         ")
        print("             [4]                 [5]                  [6]")
        print("=========================================================")
        input2 = input("echo:")
        if input2 == '1':
            print("┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓")
            print("┃ club:          ┃ no club:       ┃")
            print("┠┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╂┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┨")
            print("┃ satori         ┃ laplus         ┃")
            print("┠────────────────╂────────────────┨")
            print("┃ moniko         ┃ meebl          ┃")
            print("┠────────────────╂────────────────┨")
            print("┃ yuki           ┃                ┃")
            print("┠────────────────╂────────────────┨")
            print("┃ naruki         ┃                ┃")
            print("┠────────────────╂────────────────┨")
            print("┃ mc             ┃                ┃")
            print("┠────────────────╂────────────────┨")
            print("┃ femk           ┃                ┃")
            print("┣┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╉────────────────┨")
            print("┃                ┃                ┃")
            print("┣━━━━━━━━━━━━━━━━╉────────────────┨")

            input3 = input("Choose-a-file:")
            if input3 == 'satori':
                        print("=========================================================")
                        print("   delet-fill[1]                 [2]              info[3]")
                        print("                                                         ")
                        print("             [4]                 [5]                  [6]")
                        print("=========================================================")
                        input2 = input("echo:")
                        if input2 == "3":
                                        print("             *             ")
                                        print("            / \            ")
                                        print("           /   \           ")
                                        print("          /     \          ")
                                        print("         /       \         ")
                                        print("        /         \        ")
                                        print("       /           \       ")
                                        print("      /             \      ")
                                        print("     /               \     ")
                                        print("    /                 \    ")
                                        print("   /                   \   ")
                                        print("  /                     \  ")
                                        print(" /                       \ ")
                                        print("┌────────────┬────────────┐ ")
                                        print("* name:      *   satori   * ")
                                        print("├────────────┼────────────┤ ")
                                        print("* club:      *            * ")
                                        print("├────────────┼────────────┤ ")
                                        print("*            *            * ")
                                        print("├────────────┼────────────┤ ")
                                        print("*            *            * ")
                                        print("└────────────┴────────────┘ ")

        if input2 == '2':
            print('text-1')
            text1 = input("texit-1:")
            print('text-2')
            text2 = input("texit-2:")
            print('text-3')
            text3 = input("texit-3:")
            print('text-4')
            text4 = input("texit-4:")
        print("══════════════════════════════════════════════════════════")
        print("┌╮ \033[32m╔═1)satori ╔═╦══════════════╦═         \033[0m ")
        print("├╯ \033[32m╠═2)moniko ║ ╠═7)           ╠═         \033[0m ")
        print("╞\033[32m══╩═3)yuki ╔═╝ ╠═8)           ╠═         \033[0m ")
        print("╞\033[32m═══════════╝   ╠═9)           ╠═         \033[0m ")
        print("╞\033[32m══╦═4)naruki   ╠═10)          ╠═         \033[0m ")
        print("├╮ \033[32m╠═5)femk     ╠═11)          ╠═         \033[0m ")
        print("└╯ \033[32m╚═6)mc       ╚═12)          ╚═         \033[0m ")
        print("══════════════════════════════════════════════════════════")
        input3 = input("speaker:")
        if input3 == '1':
            print('satori-1:',text1)
            print('satori-2:',text2)
            print('satori-3:',text3)
            print('satori-4:',text4)
        if input3 == '2':
            print('moniko-1:',text1)
            print('moniko-2:',text2)
            print('moniko-3:',text3)
            print('moniko-4:',text4)
        if input3 == '3':
            print('yuki-1:',text1)
            print('yuki-2:',text2)
            print('yuki-3:',text3)
            print('yuki-4:',text4)
        if input3 == '4':
            print('naruki-1:',text1)
            print('naruki-2:',text2)
            print('naruki-3:',text3)
            print('naruki-4:',text4)
        if input3 == '5':
            print('femk-1:',text1)
            print('femk-2:',text2)
            print('femk-3:',text3)
            print('femk-4:',text4)
        if input3 == '6':
            print('mc-1:',text1)
            print('mc-2:',text2)
            print('mc-3:',text3)
            print('mc-4:',text4)
        else:
            exit()
